SELECT * FROM [dbo].[PA1$];

--1.Which apps have the highest rating in the given available dataset?
SELECT App, MAX(Rating) AS Rating FROM PA1$
GROUP BY App
ORDER BY Rating DESC;

--2.What are the number of installs and reviews for the above apps? Return the apps with the highest reviews to the top.
SELECT App, MAX(Installs) AS No_Installs, MAX(Reviews) AS No_Reviews FROM PA1$
WHERE Rating=5
GROUP BY App
ORDER BY MAx(Reviews) DESC;

--3.Which app has the highest number of reviews? Also, mention the number of reviews and category of the app
SELECT App,Category, MAX(Reviews) AS Total_Reviews FROM PA1$
GROUP BY App,Category
ORDER BY MAX(Reviews) DESC;

--4.What is the total amount of revenue generated by the google play store by hosting apps? 
--(Whenever a user buys apps  from the google play store, the amount is considered in the revenue)
SELECT SUM(Installs*Price) AS REVENUE FROM PA1$;

--5.Which Category of google play store apps has the highest number of installs? also, find out the total number of installs for that particular category.
SELECT Category,SUM(Installs) AS Total_Installs FROM PA1$
GROUP BY Category
ORDER BY SUM(Installs) DESC;

--6.Which Genre has the most number of published apps?
SELECT TOP 1 Genres, COUNT(App) AS Total_Published_Apps FROM [dbo].[PA1$]
GROUP BY Genres
ORDER BY COUNT(App) DESC;

--7.Provide the list of all games ordered in such a way that the game that has the highest number of installs is displayed on the top
--(to avoid duplicate results use distinct)
SELECT DISTINCT(App),MAX(Installs) AS Maximum_Installs FROM PA1$
WHERE Category='Game'
GROUP BY App
ORDER BY MAX(Installs) DESC;

--8.Provide the list of apps that can work on android version 4.0.3 and UP.
SELECT [App] FROM [dbo].[PA1$]
WHERE [Android_Ver]='4.0.3 and Up';

--9.How many apps from the given data set are free? Also, provide the number of paid apps.
SELECT [Type],COUNT([Type]) AS Total_Apps FROM [dbo].[PA1$]
GROUP BY [Type] ;

--10.Which is the best dating app? (Best dating app is the one having the highest number of Reviews)
SELECT TOP 1 [App], MAX([Reviews]) AS Max_Reviews FROM [dbo].[PA1$]
WHERE [Category]='Dating'
GROUP BY [App]
ORDER BY MAX([Reviews]) DESC;

select* from [dbo].[Playstore_Review$];

--11.Get the number of reviews having positive sentiment and number of reviews having negative sentiment for the app 10 best foods for you and compare them.
SELECT App,Sentiment,COUNT(Sentiment) AS Number_Reviews FROM [dbo].[Playstore_Review$] 
WHERE App='10 best foods for you' AND Sentiment NOT IN ('Neutral')
GROUP BY Sentiment,App
ORDER BY COUNT(Sentiment);

--12.Which comments of ASUS SuperNote have sentiment polarity and sentiment subjectivity both as 1?
SELECT App,Translated_review, Sentiment_Polarity, Sentiment_Subjectivity FROM [dbo].[Playstore_Review$]
WHERE App='ASUS SuperNote'
GROUP BY App,Translated_review, Sentiment_Polarity, Sentiment_Subjectivity
HAVING [Sentiment_Polarity]=1 AND [Sentiment_Subjectivity]=1;

--13.Get all the neutral sentiment reviews for the app Abs Training-Burn belly fat 
SELECT App,Translated_review,Sentiment FROM [dbo].[Playstore_Review$]
WHERE App='Abs Training-Burn belly fat'
GROUP BY App,Translated_review,Sentiment
HAVING ([Sentiment]='NEUTRAL');

--14.Extract all negative sentiment reviews for Adobe Acrobat Reader with their sentiment polarity and sentiment subjectivity
SELECT Translated_Review,Sentiment_Polarity, Sentiment_Subjectivity FROM [dbo].[Playstore_Review$]
WHERE App='Adobe Acrobat Reader'
GROUP BY App,Translated_review,Sentiment, Sentiment_Polarity, Sentiment_Subjectivity
HAVING ([Sentiment]='Negative');
